# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Partner' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Partner

 pod 'AFNetworking'
 pod 'MyLayout'
  target 'PartnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PartnerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
